export { default as IconGadgetarium } from './icon-gadgetarium';
export { default as IconPinkTree } from './icon-pink-tree';
export { default as IconCertificate } from './icon-сertificate';
export { default as IconTools } from './icon-tools';
export { default as IconCreditCard } from './icon-credit-card';
export { default as IconHands } from './icon-hands';
export { default as IconBigCar } from './icon-big-car';
export { default as IconWallet } from './icon-wallet';
export { default as IconKamazCar } from './icon-kamaz-car';
